language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - python -m pip install django-polls/dist/django-polls-0.1.tar.gz
script:
    - coverage run manage.py test polls

after_success:
    - bash <(curl -s https://codecov.io/bash)
